### ISSUE TITLE
you dont exist

### ISSUE THREAD

**Issue by Exzcgal** [3kh0/portfolio-vite#1]
youre a shell for the government to get money out of WAKE UP 3KH0 WAKE UP WAKE UP

**Comment by sushiguy11** [comment]
NO BRO

**Comment by 3kh0** [comment]
I am sorry, but Daddy Joe Biden disagrees with that statement; therefore, you are incorrect. Please cease to exist now.

**Comment by Exzcgal** [comment]
id rather live in joe bidens america than 3kh0s github

**Comment by 3kh0** [comment]
Not my president

**Comment by Mazedotexe** [comment]
> id rather live in joe bidens america than 3kh0s github

disagree
