### ISSUE TITLE
hey echo...

### ISSUE THREAD

**Issue by Mazedotexe** [3kh0/portfolio-vite#12]
@3kh0 your goal is $25 a month through sponsors, i've been sponsoring you $3 a month for some time, but if i just switch to $5 a month, you'll reach your goal. convince me to :)

**Comment by 3kh0** [comment]
You will get my eternal love, and it supports me a lot with what I do!

**Comment by Mazedotexe** [comment]
> You will get my eternal love, and it supports me a lot with what I do!

On a scale of one to ten, how much eternal love? 😉

**Comment by 3kh0** [comment]
12
